import { Injectable } from '@nestjs/common';

export interface ExportOptions {
  format: 'txt' | 'md' | 'html' | 'json';
  title?: string;
  metadata?: Record<string, any>;
}

@Injectable()
export class ExportService {
  /**
   * Exporta una respuesta de IA en el formato especificado
   */
  exportResponse(
    question: string,
    answer: string,
    sources: any[],
    options: ExportOptions,
  ): { content: string; contentType: string; extension: string; filename: string } {
    const timestamp = new Date().toISOString();
    const title = options.title || 'Geronimo AI Response';

    let content: string;
    let contentType: string;
    let extension: string;

    switch (options.format) {
      case 'md':
        content = this.exportAsMarkdown(question, answer, sources, title, timestamp);
        contentType = 'text/markdown';
        extension = 'md';
        break;

      case 'html':
        content = this.exportAsHTML(question, answer, sources, title, timestamp);
        contentType = 'text/html';
        extension = 'html';
        break;

      case 'json':
        content = this.exportAsJSON(question, answer, sources, options.metadata);
        contentType = 'application/json';
        extension = 'json';
        break;

      case 'txt':
      default:
        content = this.exportAsText(question, answer, sources, title, timestamp);
        contentType = 'text/plain';
        extension = 'txt';
        break;
    }

    const filename = `${this.sanitizeFilename(title)}_${Date.now()}.${extension}`;

    return { content, contentType, extension, filename };
  }

  private exportAsText(
    question: string,
    answer: string,
    sources: any[],
    title: string,
    timestamp: string,
  ): string {
    let text = `${title}\n`;
    text += `${'='.repeat(title.length)}\n\n`;
    text += `Generated: ${new Date(timestamp).toLocaleString()}\n\n`;
    text += `QUESTION:\n${'-'.repeat(80)}\n${question}\n\n`;
    text += `ANSWER:\n${'-'.repeat(80)}\n${answer}\n\n`;

    if (sources && sources.length > 0) {
      text += `SOURCES:\n${'-'.repeat(80)}\n`;
      sources.forEach((source, index) => {
        text += `[${index + 1}] ${source.path || source.title || 'Unknown'}\n`;
        if (source.projectId) text += `    Project: ${source.projectId}\n`;
      });
      text += '\n';
    }

    text += `\n${'-'.repeat(80)}\n`;
    text += `Generated by Geronimo - AI Documentation Assistant\n`;

    return text;
  }

  private exportAsMarkdown(
    question: string,
    answer: string,
    sources: any[],
    title: string,
    timestamp: string,
  ): string {
    let md = `# ${title}\n\n`;
    md += `**Generated:** ${new Date(timestamp).toLocaleString()}\n\n`;
    md += `---\n\n`;
    md += `## Question\n\n${question}\n\n`;
    md += `## Answer\n\n${answer}\n\n`;

    if (sources && sources.length > 0) {
      md += `## Sources\n\n`;
      sources.forEach((source, index) => {
        md += `${index + 1}. **${source.path || source.title || 'Unknown'}**\n`;
        if (source.projectId) md += `   - Project: \`${source.projectId}\`\n`;
      });
      md += '\n';
    }

    md += `---\n\n`;
    md += `*Generated by Geronimo - AI Documentation Assistant*\n`;

    return md;
  }

  private exportAsHTML(
    question: string,
    answer: string,
    sources: any[],
    title: string,
    timestamp: string,
  ): string {
    const html = `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(title)}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f5f5f5;
      color: #333;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    h1 {
      color: #1a1a1a;
      border-bottom: 3px solid #4a9eff;
      padding-bottom: 10px;
    }
    h2 {
      color: #2c3e50;
      margin-top: 30px;
    }
    .metadata {
      color: #666;
      font-size: 0.9em;
      margin-bottom: 20px;
    }
    .question {
      background: #f0f7ff;
      padding: 20px;
      border-left: 4px solid #4a9eff;
      border-radius: 4px;
      margin: 20px 0;
    }
    .answer {
      line-height: 1.6;
      margin: 20px 0;
      white-space: pre-wrap;
    }
    .sources {
      background: #f9f9f9;
      padding: 20px;
      border-radius: 4px;
      margin: 20px 0;
    }
    .sources ul {
      list-style: none;
      padding: 0;
    }
    .sources li {
      padding: 10px;
      margin: 5px 0;
      background: white;
      border-left: 3px solid #4a9eff;
      border-radius: 3px;
    }
    .footer {
      text-align: center;
      color: #999;
      font-size: 0.85em;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #eee;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>${this.escapeHtml(title)}</h1>
    <div class="metadata">
      <strong>Generated:</strong> ${new Date(timestamp).toLocaleString()}
    </div>

    <h2>Question</h2>
    <div class="question">
      ${this.escapeHtml(question)}
    </div>

    <h2>Answer</h2>
    <div class="answer">
      ${this.escapeHtml(answer)}
    </div>

    ${sources && sources.length > 0 ? `
    <h2>Sources</h2>
    <div class="sources">
      <ul>
        ${sources.map((source, index) => `
        <li>
          <strong>${index + 1}. ${this.escapeHtml(source.path || source.title || 'Unknown')}</strong>
          ${source.projectId ? `<br><small>Project: ${this.escapeHtml(source.projectId)}</small>` : ''}
        </li>
        `).join('')}
      </ul>
    </div>
    ` : ''}

    <div class="footer">
      Generated by Geronimo - AI Documentation Assistant
    </div>
  </div>
</body>
</html>`;

    return html;
  }

  private exportAsJSON(
    question: string,
    answer: string,
    sources: any[],
    metadata?: Record<string, any>,
  ): string {
    const data = {
      question,
      answer,
      sources,
      metadata: {
        ...metadata,
        generatedAt: new Date().toISOString(),
        generator: 'Geronimo AI Documentation Assistant',
      },
    };

    return JSON.stringify(data, null, 2);
  }

  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }

  private sanitizeFilename(filename: string): string {
    return filename
      .replace(/[^a-z0-9]/gi, '_')
      .replace(/_+/g, '_')
      .toLowerCase();
  }
}
